// <auto-generated />
using System;
using Glut.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Glut.Migrations
{
    [DbContext(typeof(EfDbContext))]
    [Migration("20190711101005_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Glut.Data.GlutProject", b =>
                {
                    b.Property<int>("GlutProjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedByUserName");

                    b.Property<DateTime>("CreatedDateTimeUtc");

                    b.Property<string>("GlutProjectName");

                    b.HasKey("GlutProjectId");

                    b.ToTable("GlutProject");
                });

            modelBuilder.Entity("Glut.Data.GlutResultItem", b =>
                {
                    b.Property<int>("GlutResultId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedByUserName");

                    b.Property<DateTime>("CreatedDateTimeUtc");

                    b.Property<DateTime>("EndDateTimeUtc");

                    b.Property<string>("Exception");

                    b.Property<string>("GlutProjectName");

                    b.Property<int>("GlutProjectRunId");

                    b.Property<long>("HeaderLength");

                    b.Property<bool>("IsSuccessStatusCode");

                    b.Property<long>("RequestSentTicks");

                    b.Property<string>("RequestUri");

                    b.Property<string>("ResponseHeaders");

                    b.Property<long>("ResponseLength");

                    b.Property<long>("ResponseTicks");

                    b.Property<DateTime>("StartDateTimeUtc");

                    b.Property<int>("StatusCode");

                    b.Property<long>("TotalLegth");

                    b.Property<long>("TotalTicks");

                    b.HasKey("GlutResultId");

                    b.ToTable("GlutResultItem");
                });
#pragma warning restore 612, 618
        }
    }
}
